baseURL = "https://www.luukvanvenrooij.nl/"
languageCode = "en-us"
title = "luukvanvenrooij.nl"
theme = "minimal"

[params]
    aboutProfilePic= "https://avatars.githubusercontent.com/u/11056665?s=400&u=4bdf1d069962e53c5b3dd7b73e01e977854e8800&v=4"
    aboutDescription= """
Welcome to my little corner of the web! As you might have guessed my name is Luuk van Venrooij and I`m an avid developer both in my professional and personal life.


Professionally I have worked on many different projects ranging from game engines, mobile apps (Android, iOS) and large industrial asset management systems. Currently I'm a fulltime opensource developer on the [Epiphany Platform](https://github.com/hitachienergy/epiphany), an industrialized automation of Kubernetes and additional services.

My private projects mostly center arround graphics and games using OpenGL/WebGL. On this website I showcase some of these projects. I also have a general love for hardware and technology and at some point I might branch out into this as well:)

If you have any questions, suggestions or comments feel free to <a href="#" onclick="javascript:Email()">contact me.</a>.
"""
    # Email for sending
    eMailUser = "luukvanvenrooij84"
    eMailDomain = "gmail.com"

    # Colors and fonts
    accent = "#429BEE"
    showBorder = true
    font = "Raleway"
    fontColor = "#FFFFFF"
    backgroundColor = "#292F33"
    headerColor = "#1F2429"
    headerFontColor = "#FFFFFF"

    # Code high
    highlight = true
    highlightStyle = "vs2015"
    highlightLanguages = ["javascript", "delphi", "bash", "json"]



[[menu.main]]
    url = "/"
    name = "About"
    weight = 1

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 2



[[menu.icon]]
    url = "#"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/seriva/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://www.youtube.com/user/seriva"
    name = "youtube"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/luuk-van-venrooij/"
    name = "linkedin"
    weight = 3

[markup.goldmark.renderer]
unsafe= true
