baseURL = "https://www.luukvanvenrooij.nl/"
languageCode = "en-us"
title = "luukvanvenrooij.nl"
theme = "minimal"

[params]
    twitterFeed = '<a class="twitter-timeline" data-theme="dark" data-width="600" href="https://twitter.com/luukvanvenrooij?ref_src=twsrc%5Etfw">Tweets by luukvanvenrooij</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>'
    githubUsername = "seriva"
    eMailUser = "luukvanvenrooij84"
    eMailDomain = "gmail.com"
    accent = "#429BEE"
    showBorder = true
    headerColor = "#1F2429"
    headerFontColor = "white"
    backgroundColor = "#292F33"
    font = "Raleway"
    fontColor = "white"
    highlight = true
    highlightStyle = "dracula"
    highlightLanguages = ["javascript", "delphi", "bash", "json"]

[[menu.main]]
    url = "/"
    name = "Blog"
    weight = 1  

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 2

 [[menu.icon]]
    url = "#"
    name = "envelope-o"
    weight = 1   

[[menu.icon]]
    url = "https://github.com/seriva/"
    name = "github"
    weight = 1   

[[menu.icon]]
    url = "https://www.youtube.com/user/seriva"
    name = "youtube"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/luuk-van-venrooij/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/luukvanvenrooij"
    name = "twitter"
    weight = 4

[markup.goldmark.renderer]
unsafe= true
